import Head from 'next/head'
import Image from 'next/image'

import {
  Flex,
  Box,
  Center,
  Right,
  Heading,
  Text,
  Button,
  Input,

  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,

  useColorMode,
  useColorModeValue
} from '@chakra-ui/react'

import {
  MoonIcon,
  SunIcon
} from '@chakra-ui/icons'

export default function Home() {
  const { toggleColorMode } = useColorMode()
  const formBackground = useColorModeValue("gray.200", "gray.700")
  const iconMode = useColorModeValue(<MoonIcon />, <SunIcon />)

  return (
    <div>
      <Head>
        <title>Berezhnev.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>

      <Flex height="100vh" alignItems="center" justifyContent="center" fontFamily='Poppins' >
        <Flex direction="column" p={15} rounded={10} background={formBackground}>

          <Tabs align='center' variant='solid-rounded' colorScheme="cyan">
            <TabList>
              <Tab _focus={{ boxShadow: "none" }}>Home</Tab>
              <Tab _focus={{ boxShadow: "none" }}>About</Tab>
              <Button ml={2} colorscheme="twitter" onClick={toggleColorMode} _focus={{ boxShadow: "none" }}>{iconMode}</Button>
            </TabList>

            <TabPanels>
              <TabPanel>
                <Heading m={22} mb={2}>Berezhnev.</Heading>
                <Text fontSize="1.2rem">A Front-End developer</Text>
              </TabPanel>
              <TabPanel>
                <Text>*some text here*</Text>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Flex>
      </Flex>

    </div>
  )
}
